import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy - Qalby Muslim",
  description: "Privacy Policy for Qalby Muslim - Learn how we handle your data, location permissions, notifications, and diagnostics.",
};

export default function PrivacyPolicyPage() {
  return (
    <main className="container-max py-20 md:py-28">
      {/* Header */}
      <div className="text-center mb-16">
        <h1 className="font-heading text-5xl md:text-6xl text-emerald font-bold">Privacy Policy</h1>
        <p className="mt-6 text-emerald/70 text-lg">For QalbyMuslim. Last updated: October 23, 2025.</p>
      </div>

      {/* Quick Summary */}
      <section className="mb-16 max-w-4xl mx-auto">
        <div className="relative overflow-hidden rounded-3xl backdrop-blur-2xl border border-emerald/20 p-8 md:p-10 bg-gradient-to-br from-white/5 via-emerald/5 to-transparent">
          <h2 className="font-heading text-3xl text-emerald mb-6 font-bold">Quick Summary</h2>
          <ul className="space-y-4 text-emerald/75">
            <li className="flex gap-3">
              <span className="text-emerald font-bold">•</span>
              <span><strong className="text-emerald">Data controller:</strong> Qalbymuslim — contact: qalbymuslim1@gmail.com</span>
            </li>
            <li className="flex gap-3">
              <span className="text-emerald font-bold">•</span>
              <span><strong className="text-emerald">Data we collect:</strong> Location (with consent), optional calendar access, notification tokens, limited device/diagnostic data, support messages, anonymized analytics/crash reports, and any information you voluntarily share.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-emerald font-bold">•</span>
              <span><strong className="text-emerald">Why we collect it:</strong> To deliver app features, send reminders you enable, improve performance, respond to support, and comply with legal obligations.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-emerald font-bold">•</span>
              <span><strong className="text-emerald">Sharing:</strong> We do not sell personal data. We only share data with processors required to provide app functionality.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-emerald font-bold">•</span>
              <span><strong className="text-emerald">Your rights:</strong> Adjust permissions on your device, request access or deletion via email, and exercise GDPR/CCPA rights where applicable.</span>
            </li>
          </ul>
        </div>
      </section>

      {/* Who We Are */}
      <section className="mb-16 max-w-4xl mx-auto">
        <h2 className="font-heading text-3xl text-emerald mb-6 font-bold">Who We Are</h2>
        <div className="rounded-2xl backdrop-blur-xl border border-emerald/20 p-8 bg-white/5">
          <p className="text-emerald/75 leading-relaxed">
            Qalbymuslim is the data controller responsible for Qalby Muslim. Contact us at <a href="mailto:qalbymuslim1@gmail.com" className="text-emerald font-semibold hover:underline">qalbymuslim1@gmail.com</a> for any privacy questions or to submit access, correction, or deletion requests. Please include "Privacy Request" in the subject line so we can respond quickly.
          </p>
        </div>
      </section>

      {/* Information We Collect */}
      <section className="mb-16 max-w-4xl mx-auto">
        <h2 className="font-heading text-3xl text-emerald mb-8 font-bold">Information We Collect</h2>
        
        <div className="space-y-6">
          {[
            {
              title: "Location (optional)",
              content: "Used to calculate prayer times and the Qibla direction for your location. Requested only when you initiate a location-based feature and with your explicit permission. Coordinates are stored locally and not uploaded except when calling third-party services.",
            },
            {
              title: "Notification Token",
              content: "Generated by your device when you enable push notifications. Stored with our push provider (Expo Notifications/EAS, Apple APNs, or Google FCM) so we can deliver reminders you turn on.",
            },
            {
              title: "Calendar Access (optional)",
              content: "Used only if you choose to add prayer or reminder events to your personal calendar. Events are created at your direction; we do not access or sync existing calendar entries.",
            },
            {
              title: "Device & Diagnostic Data",
              content: "Includes device type, operating system, app version, IP address, crash logs, and limited usage statistics. Helps us diagnose issues, combat fraud, and understand how features perform.",
            },
            {
              title: "Support Requests",
              content: "When you contact us, we receive the name, email, and message you provide to resolve your inquiry.",
            },
            {
              title: "Analytics & Crash Reporting (optional)",
              content: "Privacy-minded tools may capture pseudonymized usage data and crash reports. This build does not include analytics SDKs by default. Where required by law, we request consent before enabling analytics.",
            },
          ].map((item, index) => (
            <div key={index} className="rounded-2xl backdrop-blur-xl border border-emerald/20 p-8 bg-white/5 hover:bg-white/10 transition-colors">
              <h3 className="font-heading text-xl text-emerald mb-3 font-bold">{item.title}</h3>
              <p className="text-emerald/75 leading-relaxed">{item.content}</p>
            </div>
          ))}
        </div>
      </section>

      {/* How We Use Your Information */}
      <section className="mb-16 max-w-4xl mx-auto">
        <h2 className="font-heading text-3xl text-emerald mb-6 font-bold">How We Use Your Information</h2>
        <div className="rounded-2xl backdrop-blur-xl border border-emerald/20 p-8 bg-white/5">
          <ul className="space-y-3 text-emerald/75">
            <li className="flex gap-3">
              <span className="text-emerald">✓</span>
              <span>Deliver core features such as prayer schedules, Qibla direction, Quran reading, and saved preferences.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-emerald">✓</span>
              <span>Send notifications and reminders you explicitly enable (e.g., daily prayer alerts).</span>
            </li>
            <li className="flex gap-3">
              <span className="text-emerald">✓</span>
              <span>Store settings locally so the app feels personalized each time you return.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-emerald">✓</span>
              <span>Analyze performance, troubleshoot crashes, and improve reliability.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-emerald">✓</span>
              <span>Provide customer support, answer questions, and resolve technical issues.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-emerald">✓</span>
              <span>Meet legal obligations, enforce our terms, and prevent misuse or fraud.</span>
            </li>
          </ul>
          <p className="mt-6 text-emerald font-semibold">We do not use your data for targeted advertising.</p>
        </div>
      </section>

      {/* Sharing & Third-Party Processing */}
      <section className="mb-16 max-w-4xl mx-auto">
        <h2 className="font-heading text-3xl text-emerald mb-6 font-bold">Sharing & Third-Party Processing</h2>
        <div className="rounded-2xl backdrop-blur-xl border border-emerald/20 p-8 bg-white/5 mb-6">
          <p className="text-emerald/75 leading-relaxed mb-6">
            We do not sell personal data. We work with processors who help operate Qalby Muslim under strict data protection agreements:
          </p>
          <ul className="space-y-3 text-emerald/75">
            <li className="flex gap-3">
              <span className="text-emerald">•</span>
              <span><strong className="text-emerald">Prayer time APIs:</strong> Aladhan, to fetch accurate schedules.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-emerald">•</span>
              <span><strong className="text-emerald">Push notification services:</strong> Expo Notifications/EAS, Apple APNs, Google FCM.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-emerald">•</span>
              <span><strong className="text-emerald">Hosting & infrastructure:</strong> Platforms such as Hostinger for web content.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-emerald">•</span>
              <span><strong className="text-emerald">Geolocation services:</strong> For reverse geocoding to display place names.</span>
            </li>
          </ul>
        </div>
        <div className="rounded-2xl backdrop-blur-xl border border-emerald/20 p-8 bg-gradient-to-br from-white/5 via-emerald/5 to-transparent">
          <h4 className="font-semibold text-emerald mb-4">Third-Party Endpoints</h4>
          <ul className="space-y-2 text-emerald/70 text-sm font-mono">
            <li>• api.aladhan.com — prayer times computation</li>
            <li>• nominatim.openstreetmap.org — reverse geocoding</li>
            <li>• worldtimeapi.org — timezone/date information</li>
            <li>• Stripe — donation payment processing</li>
          </ul>
        </div>
      </section>

      {/* Your Rights & Choices */}
      <section className="mb-16 max-w-4xl mx-auto">
        <h2 className="font-heading text-3xl text-emerald mb-8 font-bold">Your Rights & Choices</h2>
        
        <div className="space-y-6">
          {[
            {
              title: "Manage Device Permissions",
              content: "Location & notifications: Adjust or revoke access via device settings. Calendar access: Decline permission; the app will not create calendar events without your approval.",
            },
            {
              title: "Data Access, Correction & Deletion",
              content: "Email qalbymuslim1@gmail.com with subject 'Privacy Request — [Access|Deletion|Other]'. Include your name, email, country of residence, and a brief summary. We verify identity where necessary and respond within 30 days.",
            },
            {
              title: "GDPR (EEA/UK) Rights",
              content: "Rights include access, correction, deletion, restriction, objection, portability, and challenges to automated decision-making. Contact us to exercise these rights.",
            },
            {
              title: "CCPA/CPRA (California) Rights",
              content: "California residents may request details about collected information, request deletion, and confirm we do not sell personal data.",
            },
          ].map((item, index) => (
            <div key={index} className="rounded-2xl backdrop-blur-xl border border-emerald/20 p-8 bg-white/5 hover:bg-white/10 transition-colors">
              <h3 className="font-heading text-xl text-emerald mb-3 font-bold">{item.title}</h3>
              <p className="text-emerald/75 leading-relaxed">{item.content}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Storage & Retention */}
      <section className="mb-16 max-w-4xl mx-auto">
        <h2 className="font-heading text-3xl text-emerald mb-6 font-bold">Storage & Retention</h2>
        <div className="rounded-2xl backdrop-blur-xl border border-emerald/20 p-8 bg-white/5">
          <ul className="space-y-3 text-emerald/75">
            <li><strong className="text-emerald">On-device storage:</strong> Preferences and cached data remain on your device until you clear them or uninstall the app.</li>
            <li><strong className="text-emerald">Support messages:</strong> Kept only as long as necessary to resolve your inquiry and up to 24 months afterward.</li>
            <li><strong className="text-emerald">Analytics/crash data:</strong> Stored in aggregated or anonymized form, generally for 12–36 months depending on the provider.</li>
          </ul>
          <p className="mt-6 text-emerald/75 leading-relaxed">
            We delete or anonymize personal data when it is no longer needed or when you request deletion, subject to legal requirements.
          </p>
        </div>
      </section>

      {/* Children's Privacy */}
      <section className="mb-16 max-w-4xl mx-auto">
        <h2 className="font-heading text-3xl text-emerald mb-6 font-bold">Children's Privacy</h2>
        <div className="rounded-2xl backdrop-blur-xl border border-emerald/20 p-8 bg-white/5">
          <p className="text-emerald/75 leading-relaxed mb-4">
            Qalby Muslim is not directed to children under 13. We do not knowingly collect personal data from children under 13. If you believe your child has provided information to us, contact us and we will delete it promptly.
          </p>
          <p className="text-emerald/75 leading-relaxed">
            Contact us at <a href="mailto:qalbymuslim1@gmail.com" className="text-emerald font-semibold hover:underline">qalbymuslim1@gmail.com</a> with the subject line "Privacy Request — Child Data" and we will take steps to remove the data as quickly as possible.
          </p>
        </div>
      </section>

      {/* Information Security */}
      <section className="mb-16 max-w-4xl mx-auto">
        <h2 className="font-heading text-3xl text-emerald mb-6 font-bold">Information Security</h2>
        <div className="rounded-2xl backdrop-blur-xl border border-emerald/20 p-8 bg-white/5">
          <p className="text-emerald/75 leading-relaxed">
            We implement reasonable technical, administrative, and physical safeguards to protect your information. No system is completely secure, so please notify us at <a href="mailto:qalbymuslim1@gmail.com" className="text-emerald font-semibold hover:underline">qalbymuslim1@gmail.com</a> immediately if you suspect an issue.
          </p>
        </div>
      </section>

      {/* Contact Us */}
      <section className="max-w-4xl mx-auto">
        <h2 className="font-heading text-3xl text-emerald mb-6 font-bold">Contact Us</h2>
        <div className="rounded-2xl backdrop-blur-xl border border-emerald/20 p-8 bg-gradient-to-br from-white/5 via-emerald/5 to-transparent">
          <p className="text-emerald/75 leading-relaxed mb-6">
            If you have questions about this Privacy Policy or wish to exercise your privacy rights, contact us:
          </p>
          <div className="space-y-3 text-emerald/75">
            <p><strong className="text-emerald">Email:</strong> <a href="mailto:qalbymuslim1@gmail.com" className="text-emerald font-semibold hover:underline">qalbymuslim1@gmail.com</a></p>
            <p><strong className="text-emerald">Subject:</strong> "Privacy Request — [Access|Deletion|Other]"</p>
            <p><strong className="text-emerald">Website:</strong> <a href="https://qalbymuslim.com/privacy-policy" target="_blank" rel="noopener noreferrer" className="text-emerald font-semibold hover:underline">https://qalbymuslim.com/privacy-policy</a></p>
          </div>
          <p className="mt-8 text-emerald/70 italic text-sm">
            We aim to acknowledge and respond to all legitimate requests within 30 days.
          </p>
        </div>
      </section>
    </main>
  );
}
